apiVersion: v1
kind: Service
metadata:
  name: api-locations
  namespace: default
spec:
  selector:
    app: api-locations
  ports:
  - protocol: TCP
    port: 5000  
    targetPort: 5000  
  type: ClusterIP  
