apiVersion: v1
kind: Service
metadata:
  name: api-register
  namespace: default
spec:
  selector:
    app: api-register
  ports:
  - protocol: TCP
    port: 5001  
    targetPort: 5001  
  type: ClusterIP  
