apiVersion: v1
kind: Service
metadata:
  name: api-login
  namespace: default
spec:
  selector:
    app: api-login
  ports:
  - protocol: TCP
    port: 5002  
    targetPort: 5002  
  type: ClusterIP  
