apiVersion: v1
kind: Service
metadata:
  name: api-database
  namespace: default
spec:
  selector:
    app: api-database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP  
