apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-database
  namespace: default
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: api-database
  template:
    metadata:
      labels:
        app: api-database
    spec:
      containers:
      - name: api-database
        image: cristian7b/zonapets/api-database:latest
        ports:
        - containerPort: 5432
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
