version: "3.9"
services:
  apiGateway:
    build:
      context: ./apiGateway
    ports:
      - "8000:8000"
    depends_on:
      - apiLocations
      - apiRegister
      - apiLogin
  apiLocations:
    build:
      context: ./apiLocations
    ports:
      - "8001:8000"
  apiRegister:
    build:
      context: ./apiRegister
    ports:
      - "8002:8000"
  apiLogin:
    build:
      context: ./apiLogin
    ports:
      - "8003:8000"
