services:
  apigateway:
    build:
      context: ./apiGateway
    image: zonapetsbackend-apigateway
    ports:
      - "8000:8000"
    depends_on:
      - apilocations
      - apiregister
      - apilogin
  apilocations:
    build:
      context: ./apiLocations
    image: zonapetsbackend-apilocations
    ports:
      - "8001:8000"
  apiregister:
    build:
      context: ./apiRegister
    image: zonapetsbackend-apiregister
    ports:
      - "8002:8000"
  apilogin:
    build:
      context: ./apiLogin
    image: zonapetsbackend-apilogin
    ports:
      - "8003:8000"
