apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  DB_NAME: "postgres"
  DB_HOST: "aws-0-sa-east-1.pooler.supabase.com"
  DB_PORT: "6543"
